### PR TITLE
Fixed list of Chinese files.

### PR DESCRIPTION
**Pull request by sebastian-nehrdich**

### CODE REVIEW

**Comment by ayya-vimala** [comment]
// Files mentioned in the lists but no json file found on server
[
"X04n0223",
]
// JSON files found on server but not mentioned in the lists 
[
"T31n1600-002",
"T31n1600-003",
]

**Comment by ayya-vimala** [comment]
T06n0220 and T07n0220 are not there in the json files either, nor in the lists.

**Comment by sebastian-nehrdich** [comment]
Regarging T06n0220 and T07n0220 we can safely ignore them.
Regarding those starting with a folio different than 001, thats indeed a bug. Will see when I find the time to fix that... Requires to regenerate everything.

**Comment by ayya-vimala** [comment]
Yes, I was afraid of that ... :-(

**Pull request merged**
