### PR TITLE
Small fix for searching Tibetan in the global search function

### PR DESCRIPTION
**Pull request by sebastian-nehrdich**

### CODE REVIEW

**Review by ayya-vimala — APPROVED** [review]

**Comment by sebastian-nehrdich** [comment]
It seems to me that the build is failing not so much because of problems in the code but because pylint is set up wrongly (exit code 24). What do you think?

**Comment by ayya-vimala** [comment]
The error is here:
api/main.py:577:29: C0201: Consider iterating the dictionary directly instead of calling .keys() (consider-iterating-dictionary)
But there are also conflicts in search_utils.py to be resolved.

**Comment by ayya-vimala** [comment]
I resolved the merge problem in Search.

**Comment by sebastian-nehrdich** [comment]
github remains a mystery to me. After I pulled this morning quite some of the code I added got lost, I guess the merge problem's solution plays a role here. Lets see, I can certainly recover it from the history! As long as github is happy now :D

**Comment by ayya-vimala** [comment]
Well, I guess you checked it all. So fine with me. Do you want to merge it?

**Pull request merged**
